/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACarousel: typeof import('ant-design-vue/es')['Carousel']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ASpace: typeof import('ant-design-vue/es')['Space']
    DefaultLayout: typeof import('./src/layout/DefaultLayout.vue')['default']
    LoginBanner: typeof import('./src/components/LoginBanner.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    LoginLogo: typeof import('./src/components/LoginLogo.vue')['default']
    PageLayout: typeof import('./src/layout/PageLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
